apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.backend.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-backend
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Values.backend.image.tag }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      initContainers:
        - name: init-db
          image: {{ .Values.image.profile }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          command:
          - "python"
          - "manage.py"
          - "create_db"
          env:
{{ include "env.project" . | indent 12 }}
{{ include "env.postgresql" . | indent 12 }}
      containers:
        - name: backend
          image: {{ .Values.image.profile }}/{{ .Values.backend.image.name }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
{{ include "env.project" . | indent 12 }}
{{ include "env.postgresql" . | indent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{- toYaml .Values.backend.resources | nindent 12 }}
