{{- if .Values.backend.ingress.enabled -}}
{{- $ingressRoute := .Values.backend.ingress.route -}}
{{- $serviceName := printf "%s-%s" .Release.Name "backend" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.backend.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  routes:
    - match: Host(`{{ $ingressRoute.hosts.blog }}`)
      kind: Rule
      services:
        - name: {{ $serviceName }}
          port: 80
  tls:
    secretName: {{ .Release.Name }}-backend
{{- end }}
